### ISSUE TITLE
RSS Feed is empty on live site.

### ISSUE THREAD

**Issue by AgoristRadio** [kennethreitz-archive/.com#4]

**Comment by AgoristRadio** [comment]
www.kennethreitz.com/feeds/all.atom.xml

**Comment by kennethreitz** [comment]
it is?

http://kennethreitz.com/feeds/all.atom.xml

**Comment by AgoristRadio** [comment]
Sorry man, my bad, bug in my firefox, working with curl.

**Comment by kennethreitz** [comment]
you had me worried for a second :)

**Comment by AgoristRadio** [comment]
Bug in my firefox. on empty profile and curl it comes up fine. Sorry to bother you.
Love your blog post on how you start with readme.

**Comment by kennethreitz** [comment]
Thanks :)
